apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ota-uk-v
spec:
  schedule: 0 */6 * * * 
  jobTemplate:
    metadata:
      name: ota-uk-v
    spec:
      template:
        metadata:
            annotations:
              iam.amazonaws.com/role: "arn:aws:iam::536099501702:role/pangeo"
        
        spec:
          serviceAccountName: daskkubernetes
          restartPolicy: Never
          containers:
            - name: ota-uk-v
              image: {{ .Values.image }}
              command: ["python", {{ .Values.script }} ]
              resources:
                limits:
                  cpu: "1"
                  memory: 2G
                requests:
                  cpu: "0.25"
                  memory: 0.5G
              volumeMounts:
                - name: scratch
                  mountPath: /scratch
                - name: s3
                  mountPath: /s3
                - name: daskernetes-config
                  mountPath: /etc/daskernetes
                  readOnly: true
              env:
                - name: DASK_KUBERNETES__WORKER_TEMPLATE_PATH
                  value: "/etc/daskernetes/worker-template.yaml"
                - name: AWS_DEFAULT_REGION
                  value: "eu-west-2"
            
          volumes:
            - name: daskernetes-config
              configMap:
                name: daskernetes-config
            - name: s3
              flexVolume:
                driver: "informaticslab/pysssix-flex-volume"
                options:
                  readonly: "true"
            - name: scratch
              flexVolume:
                driver: "informaticslab/goofys-flex-volume"
                options:
                  bucket: "informatics-pangeo-scratch"
                  dirMode: "0777"
                  fileMode: "0777"

          restartPolicy: Never
      backoffLimit: 4